# -*- coding: utf-8 -*-
"""final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GS4UTLtaSSRseQ_FN-KTlFThMRzmCKRT
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/AI/Dataset/Kaggle Gen z - genz_mental_wellness_synthetic_dataset.csv')

# Display the first 5 rows of the DataFrame after dropping 'source'
display(df.head())

"""Now that the data is loaded and the 'source' column has been removed, we can proceed with the preprocessing steps.

### Handling Missing Values

First, let's check for any missing values in the dataset.
"""

# Check for missing values
missing_values = df.isnull().sum()
print("Missing values in each column:")
print(missing_values[missing_values > 0])

"""### Removing 'Kaggle' Column

As requested, let's remove the 'Kaggle' column from the dataset.
"""

# Drop the 'Kaggle' column if it exists
if 'Kaggle' in df.columns:
    df = df.drop(columns=['Kaggle'])
    print("Column 'Kaggle' dropped successfully.")
else:
    print("Column 'Kaggle' not found in the DataFrame.")

# Display the first 5 rows of the DataFrame after dropping 'Kaggle' to confirm
display(df.head())

"""### Data Transformation (Categorical to Numerical)

Clustering algorithms typically require numerical input. Let's identify categorical columns and convert them using one-hot encoding.
"""

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print(f"Categorical columns identified: {list(categorical_cols)}")

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("\nDataFrame after one-hot encoding:")
display(df_encoded.head())

"""### Handling Outliers (Deteksi & Penanganan Pencilan)

We will use the Interquartile Range (IQR) method to detect and handle outliers. Outliers can significantly affect clustering results, so it's important to address them. For this task, we will cap the outliers (replace them with the upper or lower bound) to retain data while mitigating their extreme influence.
"""

# Identify numerical columns for outlier detection
numerical_cols = df_encoded.select_dtypes(include=['int64', 'float64']).columns

# Exclude 'Age' if it's considered a feature that shouldn't be capped (domain specific decision)
# For this general purpose, we'll include all numerical for demonstration.

# Apply IQR method to detect and cap outliers
for col in numerical_cols:
    Q1 = df_encoded[col].quantile(0.25)
    Q3 = df_encoded[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Cap outliers: replace values below lower_bound with lower_bound, and above upper_bound with upper_bound
    df_encoded[col] = df_encoded[col].clip(lower=lower_bound, upper=upper_bound)
    print(f"Outliers in column '{col}' capped. Lower bound: {lower_bound:.2f}, Upper bound: {upper_bound:.2f}")

print("\nDataFrame after outlier capping:")
display(df_encoded.head())

"""### Feature Selection / Dimensionality Reduction (PCA)

To manage the complexity of our dataset and potentially improve clustering performance, we'll apply Principal Component Analysis (PCA). PCA helps reduce the number of features by transforming the original features into a new set of orthogonal (uncorrelated) components, ordered by the amount of variance they explain. We will decide on the number of components to retain based on explained variance.
"""

from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

# Identify numerical columns for scaling
numerical_cols = df_encoded.select_dtypes(include=['int64', 'float64']).columns

# Instantiate StandardScaler
scaler = StandardScaler()

# Apply Z-Score scaling to the numerical columns
df_scaled = df_encoded.copy() # Create a copy to avoid modifying df_encoded directly
df_scaled[numerical_cols] = scaler.fit_transform(df_encoded[numerical_cols])

print("DataFrame after Z-Score normalization:")
display(df_scaled.head())

# Initialize PCA without specifying n_components to inspect explained variance ratio
pca = PCA()
pca.fit(df_scaled)

# Plot the explained variance ratio to determine the number of components
plt.figure(figsize=(10, 6))
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('Number of Components')
plt.ylabel('Cumulative Explained Variance')
plt.title('Explained Variance vs. Number of Components')
plt.grid(True)
plt.show()

# Based on the plot, we can decide on the number of components.
# For example, let's aim for components that explain 95% of the variance.
# Find the number of components for 95% explained variance
cumulative_variance = np.cumsum(pca.explained_variance_ratio_)
num_components = np.where(cumulative_variance >= 0.95)[0][0] + 1 # +1 because of 0-based indexing

print(f"Number of components to explain 95% variance: {num_components}")

# Apply PCA with the chosen number of components
pca = PCA(n_components=num_components)
df_pca = pca.fit_transform(df_scaled)

# Create a DataFrame from the PCA results
df_pca = pd.DataFrame(df_pca, columns=[f'PC_{i+1}' for i in range(num_components)])

print("DataFrame after PCA:")
display(df_pca.head())

"""### Determining the Optimal Number of Clusters (k)

Before applying clustering algorithms, it's crucial to determine an appropriate number of clusters (k). We will use two common methods for this: the Elbow Method and the Silhouette Score.

#### 1. Elbow Method

The Elbow Method looks at the total within-cluster sum of squares (WCSS) as a function of the number of clusters. WCSS decreases as the number of clusters increases, and the 'elbow' point (where the rate of decrease sharply changes) is considered a good indicator for the optimal 'k'.
"""

from sklearn.cluster import KMeans

wcss = []
# Try different numbers of clusters, for example from 1 to 10
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init=10) # n_init to suppress warning
    kmeans.fit(df_pca)
    wcss.append(kmeans.inertia_)

# Plotting the Elbow Method graph
plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--')
plt.title('Elbow Method For Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Within-Cluster Sum of Squares (WCSS)')
plt.grid(True)
plt.show()

"""#### 2. Silhouette Score

The Silhouette Score measures how similar an object is to its own cluster compared to other clusters. The score ranges from -1 to +1, where a high value indicates that the object is well matched to its own cluster and poorly matched to neighboring clusters. A score close to +1 indicates good clustering. We'll calculate the average silhouette score for various 'k' values.
"""

from sklearn.metrics import silhouette_score

silhouette_scores = []
# Iterate for k from 2 to 10 (Silhouette Score requires at least 2 clusters)
for i in range(2, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init=10)
    kmeans.fit(df_pca)
    score = silhouette_score(df_pca, kmeans.labels_)
    silhouette_scores.append(score)

# Plotting the Silhouette Score graph
plt.figure(figsize=(10, 6))
plt.plot(range(2, 11), silhouette_scores, marker='o', linestyle='--')
plt.title('Silhouette Score For Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.grid(True)
plt.show()

"""### Comparing Clustering Results for k=2, k=3, and k=4

Based on the Elbow Method and Silhouette Score, we identified potential optimal `k` values. Now, let's explicitly run K-Means for `k=2`, `k=3`, and `k=4` and compare their results through visualization and re-evaluating the Silhouette Score.
"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

k_values = [2, 3, 4]
cluster_results = {}

print("--- K-Means Clustering Results ---")
for k in k_values:
    kmeans = KMeans(n_clusters=k, init='k-means++', random_state=42, n_init=10)
    cluster_labels = kmeans.fit_predict(df_pca)
    silhouette_avg = silhouette_score(df_pca, cluster_labels)

    cluster_results[k] = {
        'labels': cluster_labels,
        'silhouette_score': silhouette_avg,
        'kmeans_model': kmeans
    }
    print(f"For k={k}: Silhouette Score = {silhouette_avg:.4f}")

print("\n--- Visualizing Clusters (2D PCA Projection) ---")

# Reduce df_pca to 2 components for visualization
pca_2d = PCA(n_components=2)
df_pca_2d = pca_2d.fit_transform(df_pca)
df_pca_2d = pd.DataFrame(df_pca_2d, columns=['PC1', 'PC2'])

plt.figure(figsize=(18, 6))

for i, k in enumerate(k_values):
    df_pca_2d['Cluster'] = cluster_results[k]['labels']

    plt.subplot(1, len(k_values), i + 1)
    sns.scatterplot(
        x='PC1',
        y='PC2',
        hue='Cluster',
        data=df_pca_2d,
        palette='viridis',
        legend='full',
        alpha=0.7
    )
    plt.title(f'K-Means Clustering with k={k} (Silhouette: {cluster_results[k]["silhouette_score"]:.2f})')
    plt.xlabel('Principal Component 1')
    plt.ylabel('Principal Component 2')
    plt.grid(True)

plt.tight_layout()
plt.show()

"""### Applying Multiple Clustering Algorithms

Having determined a potential optimal `k` and compared K-Means for a few values, we will now apply three different clustering algorithms to the PCA-reduced data (`df_pca`). We'll evaluate each using appropriate metrics and visualize their results using the 2D PCA projection for comparison.

#### 1. K-Means Clustering (with k=2)

Based on our previous analysis (especially the Silhouette Score), `k=2` showed the most distinct separation. We will re-run K-Means with `k=2` and include it in our comparison.
"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# K-Means with k=2
k_optimal = 2
kmeans_model = KMeans(n_clusters=k_optimal, init='k-means++', random_state=42, n_init=10)
kmeans_labels = kmeans_model.fit_predict(df_pca)
kmeans_silhouette = silhouette_score(df_pca, kmeans_labels)

print(f"K-Means (k={k_optimal}) Silhouette Score: {kmeans_silhouette:.4f}")

# Add K-Means labels to df_pca_2d for visualization
df_pca_2d['KMeans_Cluster'] = kmeans_labels

plt.figure(figsize=(8, 6))
sns.scatterplot(
    x='PC1',
    y='PC2',
    hue='KMeans_Cluster',
    data=df_pca_2d,
    palette='viridis',
    legend='full',
    alpha=0.7
)
plt.title(f'K-Means Clustering (k={k_optimal}) (Silhouette: {kmeans_silhouette:.2f})')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.show()

"""#### 2. Agglomerative Hierarchical Clustering

Agglomerative clustering is a 'bottom-up' approach where each data point starts as its own cluster, and then pairs of clusters are merged as one moves up the hierarchy. We'll use a fixed number of clusters (e.g., `n_clusters=2` for comparison with K-Means) and the 'ward' linkage method.
"""

from sklearn.cluster import AgglomerativeClustering

# Agglomerative Clustering with n_clusters=2
agg_model = AgglomerativeClustering(n_clusters=2, linkage='ward')
agg_labels = agg_model.fit_predict(df_pca)
agg_silhouette = silhouette_score(df_pca, agg_labels)

print(f"Agglomerative Clustering (n_clusters=2) Silhouette Score: {agg_silhouette:.4f}")

# Add Agglomerative labels to df_pca_2d for visualization
df_pca_2d['Agg_Cluster'] = agg_labels

plt.figure(figsize=(8, 6))
sns.scatterplot(
    x='PC1',
    y='PC2',
    hue='Agg_Cluster',
    data=df_pca_2d,
    palette='viridis',
    legend='full',
    alpha=0.7
)
plt.title(f'Agglomerative Clustering (n_clusters=2) (Silhouette: {agg_silhouette:.2f})')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.show()

"""#### 3. DBSCAN (Density-Based Spatial Clustering of Applications with Noise)

DBSCAN is a density-based clustering algorithm that groups together points that are closely packed together, marking as outliers points that lie alone in low-density regions. It does not require specifying the number of clusters beforehand. We'll need to choose appropriate `eps` (maximum distance between two samples for one to be considered as in the neighborhood of the other) and `min_samples` (number of samples in a neighborhood for a point to be considered as a core point).
"""

from sklearn.cluster import DBSCAN

# For DBSCAN, finding optimal parameters (eps, min_samples) is crucial and often requires experimentation.
# A common approach for 'eps' is to use a k-distance graph (e.g., k=min_samples-1). For now, we'll pick some values.
# A min_samples value is often chosen based on dimensionality (e.g., 2*dimensions or higher).

# Let's start with some illustrative parameters. These might need tuning for better results.
dbsc_model = DBSCAN(eps=1.5, min_samples=5)
# 'eps' and 'min_samples' are highly dataset-dependent. Adjust these based on data density.

dbsc_labels = dbsc_model.fit_predict(df_pca)

# DBSCAN might produce noise points (label -1). Silhouette score needs to handle these.
# We calculate silhouette score only for points that are assigned to a cluster (not noise).
if len(set(dbsc_labels)) > 1 and -1 in dbsc_labels:
    dbsc_silhouette = silhouette_score(df_pca[dbsc_labels != -1], dbsc_labels[dbsc_labels != -1])
elif len(set(dbsc_labels)) > 1 and -1 not in dbsc_labels:
    dbsc_silhouette = silhouette_score(df_pca, dbsc_labels)
else: # All points are noise or all points are in one cluster
    dbsc_silhouette = -1 # Or NaN, or print a message indicating no valid clusters for score

print(f"DBSCAN Silhouette Score (excluding noise): {dbsc_silhouette:.4f}")
print(f"Number of clusters found by DBSCAN (excluding noise): {len(set(dbsc_labels)) - (1 if -1 in dbsc_labels else 0)}")
print(f"Number of noise points: {list(dbsc_labels).count(-1)}")

# Add DBSCAN labels to df_pca_2d for visualization
df_pca_2d['DBSCAN_Cluster'] = dbsc_labels

plt.figure(figsize=(8, 6))
sns.scatterplot(
    x='PC1',
    y='PC2',
    hue='DBSCAN_Cluster',
    data=df_pca_2d,
    palette='viridis',
    legend='full',
    alpha=0.7
)
plt.title(f'DBSCAN Clustering (Silhouette: {dbsc_silhouette:.2f})')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.show()
